version: 2
jobs:
  build_test:
    docker:
      - image: circleci/node:7.10
    parallelism: 2
    steps:
      - run: yarn build
      - run: yarn test
  install_deps:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: yarn install
workflows:
  version: 2
  build_and_test:
    jobs:
      - install_deps
      - build_test
        requires:
          - install_deps
