version: 2
jobs:
  install:
    steps:
      - restore_cache:
        name: Restore Yarn Package Cache
        keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: yarn build
  test:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: yarn
      - run: yarn lint
      - run: yarn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - build
        requires:
          - install
      - test
        requires:
          - install
