version: 2
jobs:
  build_test:
    docker:
      - image: circleci/node:7.10
    parallelism: 2
    steps:
      - run: yarn build
      - run: yarn test
  install:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - restore_cache:
          keys: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - build_test:
          requires:
            - install
