version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: yarn build
  test:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: yarn lint
      - run: yarn test
  install:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - build
        requires:
          - install
      - test
        requires:
          - install