version: 2
jobs:
  build_test:
    docker:
      - image: circleci/node:7.10
    parallelism: 2
    steps:
      - run: yarn build
      - run: yarn test
  install:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: yarn install
workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - build_test:
          requires:
            - install
